import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner/banner'
import NavBar from '../components/nav/navbar'
import Card from '../components/card/card'
import SectionCards from '../components/card/section-cards'

import { getVideos } from "../lib/videos"

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney%20trailer")

  const productivityVideos = await getVideos("productivity")

  const travelVideos = await getVideos("travel")

  return { props: { disneyVideos, travelVideos, productivityVideos }}
}

export default function Home({ disneyVideos, travelVideos, productivityVideos }) {

  console.log({ disneyVideos })

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="daniel@mail.com" />
      <Banner 
        title="Clifford the red dog" 
        subTitle="A very cute dog" 
        imgUrl="/static/clifford.webp" 
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Travel" videos={travelVideos} size="small" />
        <SectionCards title="Productivity" videos={productivityVideos} size="medium" />
        <SectionCards title="Popular" videos={disneyVideos} size="small" />
      </div>

    </div>
  )
}
